export const ENV = {
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_REFRESH_SECRET_KEY: 'JWT_REFRESH_SECRET_KEY',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',

  SUPER_ADMIN_FULL_NAME: 'SUPER_ADMIN_FULL_NAME',
  SUPER_ADMIN_EMAIL: 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASSWORD: 'SUPER_ADMIN_PASSWORD',
} as const;
