export const ENV = {
  // Application
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  // Client
  CLIENT_URL: 'CLIENT_URL',

  // Database
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USERNAME: 'DATABASE_USERNAME',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',

  // JWT
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',

  // Refresh Token
  REFRESH_TOKEN_TTL_DAYS: 'REFRESH_TOKEN_TTL_DAYS',

  // Cookies
  COOKIE_NAME: 'COOKIE_NAME',
  COOKIE_SECURE: 'COOKIE_SECURE',
  COOKIE_SAME_SITE: 'COOKIE_SAME_SITE',

  // Super Admin
  SUPER_ADMIN_EMAIL: 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASSWORD: 'SUPER_ADMIN_PASSWORD',
  SUPER_ADMIN_FULL_NAME: 'SUPER_ADMIN_FULL_NAME',
} as const;
